### ISSUE TITLE
Semi-shift Convolution in repo is different from paper description

### ISSUE THREAD

**Issue by shkarupa-alex** [poppinace/fade#2]
In paper you wrote
```
To implement this efficiently, we split the process to 4 sub-processes; each sub-process 
focuses on the top-left, top-right, bottom-left, and bottom-right windows, respectively.
Different sub-processes have also different prepossessing strategies. For example, for the 
top-left sub-process, we add full padding to the decoder feature, but only add padding on 
top and left to the encoder feature. Then all the top-left window correspondences can be 
satisfied by setting stride of 1 for the decoder feature and 2 for the encoder feature. Finally, 
after a few memory operations, the four sub-outputs can be reassembled to the expected 
upsampling kernel, and the kernel is used to reassemble decoder features to generate 
pre-upsampled features, as shown in Fig. 3(b).
```

But i don't see any splitting in 4 sub-processes or padding in https://github.com/poppinace/fade/blob/main/FADE_L2H.py#L45
I see described method in https://github.com/poppinace/fade/blob/main/FADE_H2L.py#L38 which is not used in current codebase.

Could you please describe what is the difference in that implementations? Which of them used to get SOTA results in your paper?

**Comment by poppinace** [comment]
The two implementations are equivalent. L2H is a more memory-efficient implementation than H2L described in the paper we find recently. You can use either one you like, but I recommend the L2H one.
